DECLARE @NAME VARCHAR(50);
DECLARE @PASSWORD NVARCHAR(50);

SET @NAME = 'BOSS';
SET @PASSWORD = '1234';

IF @NAME='BOSS' AND @PASSWORD='1234'
BEGIN
	PRINT 'The Boss Is Here You Are Welcome';
END
ELSE 
BEGIN
	PRINT 'Sorry I Cant Open To Any One Except BOSS';
END